spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 2000000
      minimum-idle: 10
      maximum-pool-size: 30
      pool-name: PostManagementHikariCP
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate.order_by.default_null_ordering: last
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.connection.charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.show-sql: true