spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              drop-target: generated/drop/drop-default-scheme.sql
              create-target: generated/create/create-default-scheme.sql